### ISSUE TITLE
As a user, when I visit the app, all movies should be displayed.

### ISSUE THREAD

**Issue by BHaddad1** [BHaddad1/cinemaquest#2]
##Description:
As a user...

- I want to see a movie hub.
- I want to be able to click a card/poster and see more information about that movie
- I want to be able to find a movie by the title
- I want a user-friendly experience. 

##Acceptance:
- Have an organized architecture on how things should be displayed
- think about the components ,forms and methods needed 
- how to display your API data
- this could be a polished Dom UI before going into iteration 3 or 4. 
- Can it be user-friendly, does it look polished?

**Comment by AndrewCerveny** [comment]
![React-workFlow](https://user-images.githubusercontent.com/104449342/216196249-4ab360ec-34d0-4246-8c5d-ffaec16378bb.svg)

**Comment by AndrewCerveny** [comment]
![project workFLOW](https://user-images.githubusercontent.com/104449342/216196553-68f59d30-6788-44f5-b38c-5f5ddc611a79.svg)

**Comment by AndrewCerveny** [comment]
![updated arch](https://user-images.githubusercontent.com/104449342/216457618-b2988af9-096c-433d-8732-ff79b3c2e269.png)
