### ISSUE TITLE
As a user, I should see movies displayed in a pleasing way that is logical and thoughtful.

### ISSUE THREAD

**Issue by BHaddad1** [BHaddad1/cinemaquest#7]
Description:
-As a user

I want to see a movie hub.
Where all my movie options are displayed to me in small poster formats.
should see the app title as well as a logo.
should be able to find a movie by title from the search bar
I should have the option to scroll down the page to see all movies.
Acceptance:

a layout of many / all movie posters in a main body.
-in the nav/ header area I should see a logo and the company title. and a search bar with a submit.
Maybe in the search bar add a placeholder to specify the search by title

**Comment by AndrewCerveny** [comment]
![WIFRE FRAME LAYOUT](https://user-images.githubusercontent.com/104449342/216189429-07eb4588-9ff1-48f2-9065-895904f77e40.svg)

**Comment by AndrewCerveny** [comment]
Description:
-As a user 
- I want to see a movie hub.
- Where all my movie options are displayed to me in small poster formats. 
- should see the app title as well as a logo. 
- should be able to find a movie by title from the search bar  
- I should have the option to scroll down the page to see all movies. 

Acceptance: 
- a layout of many / all movie posters in a main body. 
-in the nav/ header area I should see a logo and the company title. and a search bar with a submit.
- Maybe in the search bar add a placeholder to specify the search by title
